# time zone
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

# set charset utf8 mysql_query()
SET character_set_results = 'utf8', character_set_client = 'utf8', character_set_connection = 'utf8', character_set_database = 'utf8', character_set_server = 'utf8';

CREATE DATABASE IF NOT EXISTS `" + DBname + "` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE DBname;
CREATE TABLE IF NOT EXISTS `accessTokens` (`id` bigint(22) NOT NULL AUTO_INCREMENT,`code` varchar(250),`accessToken` varchar(250),`refreshToken` varchar(250),`tokenType` varchar(250),`expiresIn` varchar(250),`refreshTime` bigint(22) DEFAULT 0,`ip` varchar(250),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',`uniqueToken` varchar(250),PRIMARY KEY (`id`),UNIQUE KEY `accessToken` (`accessToken`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;
CREATE TABLE IF NOT EXISTS `accessTokensInactive` (`id` bigint(22) NOT NULL AUTO_INCREMENT,`code` text,`accessToken` text,`refreshToken` text,`tokenType` varchar(250),`expiresIn` varchar(250),`refreshTime` bigint(22) DEFAULT 0,`ip` varchar(250),`time` bigint(22) DEFAULT 0,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;
CREATE TABLE IF NOT EXISTS `users` (`id` bigint(22) NOT NULL AUTO_INCREMENT,`email` varchar(200),`nick` varchar(50),`pass` varchar(32),`country` varchar(100) DEFAULT NULL,`mobile` varchar(100) DEFAULT NULL,`www` varchar(250) DEFAULT NULL,`about` text,`trader` char(1) DEFAULT '0',`ip` varchar(100),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',PRIMARY KEY (`id`),UNIQUE KEY `nick` (`nick`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;
CREATE TABLE IF NOT EXISTS `accounts` (`id` bigint NOT NULL AUTO_INCREMENT,`accountId` varchar(250),`accountNumber` varchar(250),`live` varchar(250),`brokerName` varchar(250),`brokerTitle` varchar(250),`brokerCode` varchar(250),`depositCurrency` varchar(250),`traderRegistrationTimestamp` varchar(250),`traderAccountType` varchar(250),`leverage` varchar(250),`leverageInCents` varchar(250),`balance` varchar(250),`deleted` varchar(250),`accountStatus` varchar(250),`swapFree` varchar(250),`ip` varchar(250),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',`unique` varchar(250),PRIMARY KEY (`id`),UNIQUE KEY `accountId`(`accountId`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;
CREATE TABLE IF NOT EXISTS `OpenPositions` (`id` bigint NOT NULL AUTO_INCREMENT,`accountId` varchar(250),`accountNumber` varchar(250),`positionId` varchar(250),`entryTimestamp` varchar(250),`utcLastUpdateTimestamp` varchar(250),`symbolName` varchar(50),`tradeSide` varchar(50),`entryPrice` decimal(10,6),`volume` decimal(50,2),`stopLoss` decimal(10,2),`takeProfit` decimal(10,2),`profit` decimal(10,2),`profitInPips` decimal(10,2),`commision` decimal(10,2),`marginRate` decimal(10,2),`swap` decimal(10,2),`currentPrice` decimal(10,6),`comment` varchar(250),`chanel` varchar(250),`label` varchar(250),`ip` varchar(250),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',`unique` varchar(250),PRIMARY KEY (`id`),UNIQUE KEY `positionId`(`positionId`),UNIQUE KEY `unique` (`accountNumber`,`positionId`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;
CREATE TABLE IF NOT EXISTS `ClosePositions` (`id` bigint NOT NULL AUTO_INCREMENT,`accountId` varchar(250),`accountNumber` varchar(250),`dealId` varchar(250),`positionId` varchar(250),`orderId` varchar(250),`tradeSide` varchar(250),`volume` decimal(50,2),`filledVolume` decimal(50,2),`symbolName` varchar(250),`commision` decimal(50,2),`executionPrice` decimal(50,6),`baseToUsdConversionRate` varchar(250),`marginRate` varchar(250),`chanel` varchar(250),`label` varchar(250),`comment` varchar(250),`createTimestamp` varchar(250),`executionTimestamp` varchar(250),`positionCloseDetails` char(1), `entryPrice` decimal(50,6),`profit` decimal(50,2),`swap` decimal(50,2),`commisionclose` decimal(50,2),`balance` decimal(50,2),`balanceVersion` varchar(50),`commentclose` varchar(250),`stopLossPrice` decimal(50,2),`takeProfitPrice` decimal(50,2),`quoteToDepositConversionRate` decimal(50,6),`closedVolume` decimal(50,2),`profitInPips` decimal(50,2),`roi` decimal(50,6),`equityBasedRoi` decimal(50,6),`equity` decimal(50,6),`ip` varchar(250),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',`unique` varchar(250),PRIMARY KEY (`id`),UNIQUE KEY `positionId`(`positionId`),UNIQUE KEY `unique` (`accountNumber`,`positionId`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;"

# New database
# string t0 = "USE " + DBname + ";";
# string t1 = "CREATE TABLE IF NOT EXISTS `accessTokens` (`id` bigint(22) NOT NULL AUTO_INCREMENT,`code` varchar(250),`accessToken` varchar(250),`refreshToken` varchar(250),`tokenType` varchar(250),`expiresIn` varchar(250),`refreshTime` bigint(22) DEFAULT 0,`ip` varchar(250),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',`uniqueToken` varchar(250),PRIMARY KEY (`id`),UNIQUE KEY `accessToken` (`accessToken`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;";
# string t2 = "CREATE TABLE IF NOT EXISTS `accessTokensInactive` (`id` bigint(22) NOT NULL AUTO_INCREMENT,`code` text,`accessToken` text,`refreshToken` text,`tokenType` varchar(250),`expiresIn` varchar(250),`refreshTime` bigint(22) DEFAULT 0,`ip` varchar(250),`time` bigint(22) DEFAULT 0,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;";
# string t3 = "CREATE TABLE IF NOT EXISTS `users` (`id` bigint(22) NOT NULL AUTO_INCREMENT,`email` varchar(200),`nick` varchar(50),`pass` varchar(32),`country` varchar(100) DEFAULT NULL,`mobile` varchar(100) DEFAULT NULL,`www` varchar(250) DEFAULT NULL,`about` text,`trader` char(1) DEFAULT '0',`ip` varchar(100),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',PRIMARY KEY (`id`),UNIQUE KEY `nick` (`nick`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;";
# string t4 = "CREATE TABLE IF NOT EXISTS `accounts` (`id` bigint NOT NULL AUTO_INCREMENT,`accountId` varchar(250),`accountNumber` varchar(250),`live` varchar(250),`brokerName` varchar(250),`brokerTitle` varchar(250),`brokerCode` varchar(250),`depositCurrency` varchar(250),`traderRegistrationTimestamp` varchar(250),`traderAccountType` varchar(250),`leverage` varchar(250),`leverageInCents` varchar(250),`balance` varchar(250),`deleted` varchar(250),`accountStatus` varchar(250),`swapFree` varchar(250),`ip` varchar(250),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',`unique` varchar(250),PRIMARY KEY (`id`),UNIQUE KEY `accountId`(`accountId`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;";
# string t5 = "CREATE TABLE IF NOT EXISTS `OpenPositions` (`id` bigint NOT NULL AUTO_INCREMENT,`accountId` varchar(250),`accountNumber` varchar(250),`positionId` varchar(250),`entryTimestamp` varchar(250),`utcLastUpdateTimestamp` varchar(250),`symbolName` varchar(50),`tradeSide` varchar(50),`entryPrice` decimal(10,6),`volume` decimal(50,2),`stopLoss` decimal(10,2),`takeProfit` decimal(10,2),`profit` decimal(10,2),`profitInPips` decimal(10,2),`commision` decimal(10,2),`marginRate` decimal(10,2),`swap` decimal(10,2),`currentPrice` decimal(10,6),`comment` varchar(250),`chanel` varchar(250),`label` varchar(250),`ip` varchar(250),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',`unique` varchar(250),PRIMARY KEY (`id`),UNIQUE KEY `positionId`(`positionId`),UNIQUE KEY `unique` (`accountNumber`,`positionId`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;";
# string t6 = "CREATE TABLE IF NOT EXISTS `ClosePositions` (`id` bigint NOT NULL AUTO_INCREMENT,`accountId` varchar(250),`accountNumber` varchar(250),`dealId` varchar(250),`positionId` varchar(250),`orderId` varchar(250),`tradeSide` varchar(250),`volume` decimal(50,2),`filledVolume` decimal(50,2),`symbolName` varchar(250),`commision` decimal(50,2),`executionPrice` decimal(50,6),`baseToUsdConversionRate` varchar(250),`marginRate` varchar(250),`chanel` varchar(250),`label` varchar(250),`comment` varchar(250),`createTimestamp` varchar(250),`executionTimestamp` varchar(250),`positionCloseDetails` char(1), `entryPrice` decimal(50,6),`profit` decimal(50,2),`swap` decimal(50,2),`commisionclose` decimal(50,2),`balance` decimal(50,2),`balanceVersion` varchar(50),`commentclose` varchar(250),`stopLossPrice` decimal(50,2),`takeProfitPrice` decimal(50,2),`quoteToDepositConversionRate` decimal(50,6),`closedVolume` decimal(50,2),`profitInPips` decimal(50,2),`roi` decimal(50,6),`equityBasedRoi` decimal(50,6),`equity` decimal(50,6),`ip` varchar(250),`time` bigint(22) DEFAULT 0,`active` char(1) DEFAULT '1',`unique` varchar(250),PRIMARY KEY (`id`),UNIQUE KEY `positionId`(`positionId`),UNIQUE KEY `unique` (`accountNumber`,`positionId`)) ENGINE=InnoDB DEFAULT CHARSET=`utf8` COLLATE=`utf8_general_ci`;";                
